export const emojis = [
  {
    code: ["1F600"],
    emoji: "😀",
    name: "grinning face",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F603"],
    emoji: "😃",
    name: "grinning face with big eyes",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F604"],
    emoji: "😄",
    name: "grinning face with smiling eyes",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F601"],
    emoji: "😁",
    name: "beaming face with smiling eyes",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F606"],
    emoji: "😆",
    name: "grinning squinting face",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F605"],
    emoji: "😅",
    name: "grinning face with sweat",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F602"],
    emoji: "😂",
    name: "face with tears of joy",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F923"],
    emoji: "🤣",
    name: "rolling on the floor laughing",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F60A"],
    emoji: "😊",
    name: "smiling face with smiling eyes",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F642"],
    emoji: "🙂",
    name: "slightly smiling face",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F643"],
    emoji: "🙃",
    name: "upside-down face",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F609"],
    emoji: "😉",
    name: "winking face",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F60D"],
    emoji: "😍",
    name: "smiling face with heart-eyes",
    category: "Smileys & Emotion",
    subcategory: "face-affection",
  },
  {
    code: ["1F970"],
    emoji: "🥰",
    name: "smiling face with hearts",
    category: "Smileys & Emotion",
    subcategory: "face-affection",
  },
  {
    code: ["1F618"],
    emoji: "😘",
    name: "face blowing a kiss",
    category: "Smileys & Emotion",
    subcategory: "face-affection",
  },
  {
    code: ["1F60B"],
    emoji: "😋",
    name: "face savoring food",
    category: "Smileys & Emotion",
    subcategory: "face-tongue",
  },
  {
    code: ["1F61B"],
    emoji: "😛",
    name: "face with tongue",
    category: "Smileys & Emotion",
    subcategory: "face-tongue",
  },
  {
    code: ["1F61C"],
    emoji: "😜",
    name: "winking face with tongue",
    category: "Smileys & Emotion",
    subcategory: "face-tongue",
  },
  {
    code: ["1F92A"],
    emoji: "🤪",
    name: "zany face",
    category: "Smileys & Emotion",
    subcategory: "face-tongue",
  },
  {
    code: ["1F913"],
    emoji: "🤓",
    name: "nerd face",
    category: "Smileys & Emotion",
    subcategory: "face-glasses",
  },
  {
    code: ["1F60E"],
    emoji: "😎",
    name: "smiling face with sunglasses",
    category: "Smileys & Emotion",
    subcategory: "face-glasses",
  },
  {
    code: ["1F973"],
    emoji: "🥳",
    name: "partying face",
    category: "Smileys & Emotion",
    subcategory: "face-hat",
  },
  {
    code: ["1F92F"],
    emoji: "🤯",
    name: "exploding head",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F624"],
    emoji: "😤",
    name: "face with steam from nose",
    category: "Smileys & Emotion",
    subcategory: "face-negative",
  },
  {
    code: ["1F621"],
    emoji: "😡",
    name: "pouting face",
    category: "Smileys & Emotion",
    subcategory: "face-negative",
  },
  {
    code: ["1F92C"],
    emoji: "🤬",
    name: "face with symbols on mouth",
    category: "Smileys & Emotion",
    subcategory: "face-negative",
  },
  {
    code: ["1F62D"],
    emoji: "😭",
    name: "loudly crying face",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F622"],
    emoji: "😢",
    name: "crying face",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F97A"],
    emoji: "🥺",
    name: "pleading face",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F631"],
    emoji: "😱",
    name: "face screaming in fear",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F628"],
    emoji: "😨",
    name: "fearful face",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F630"],
    emoji: "😰",
    name: "anxious face with sweat",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F634"],
    emoji: "😴",
    name: "sleeping face",
    category: "Smileys & Emotion",
    subcategory: "face-sleepy",
  },
  {
    code: ["1F914"],
    emoji: "🤔",
    name: "thinking face",
    category: "Smileys & Emotion",
    subcategory: "face-hand",
  },
  {
    code: ["1F917"],
    emoji: "🤗",
    name: "hugging face",
    category: "Smileys & Emotion",
    subcategory: "face-hand",
  },
  {
    code: ["1F62C"],
    emoji: "😬",
    name: "grimacing face",
    category: "Smileys & Emotion",
    subcategory: "face-concerned",
  },
  {
    code: ["1F644"],
    emoji: "🙄",
    name: "face with rolling eyes",
    category: "Smileys & Emotion",
    subcategory: "face-neutral",
  },
  {
    code: ["1F607"],
    emoji: "😇",
    name: "smiling face with halo",
    category: "Smileys & Emotion",
    subcategory: "face-hat",
  },
  {
    code: ["1F929"],
    emoji: "🤩",
    name: "star-struck",
    category: "Smileys & Emotion",
    subcategory: "face-smiling",
  },
  {
    code: ["1F637"],
    emoji: "😷",
    name: "face with medical mask",
    category: "Smileys & Emotion",
    subcategory: "face-unwell",
  },
  {
    code: ["1F92E"],
    emoji: "🤮",
    name: "face vomiting",
    category: "Smileys & Emotion",
    subcategory: "face-unwell",
  },
  {
    code: ["1F927"],
    emoji: "🤧",
    name: "sneezing face",
    category: "Smileys & Emotion",
    subcategory: "face-unwell",
  },
  {
    code: ["1F610"],
    emoji: "😐",
    name: "neutral face",
    category: "Smileys & Emotion",
    subcategory: "face-neutral",
  },
  {
    code: ["1F611"],
    emoji: "😑",
    name: "expressionless face",
    category: "Smileys & Emotion",
    subcategory: "face-neutral",
  },
  {
    code: ["1F44D"],
    emoji: "👍",
    name: "thumbs up",
    category: "People & Body",
    subcategory: "hand-fingers-closed",
  },
  {
    code: ["1F44E"],
    emoji: "👎",
    name: "thumbs down",
    category: "People & Body",
    subcategory: "hand-fingers-closed",
  },
  {
    code: ["1F44F"],
    emoji: "👏",
    name: "clapping hands",
    category: "People & Body",
    subcategory: "hands",
  },
  {
    code: ["1F64C"],
    emoji: "🙌",
    name: "raising hands",
    category: "People & Body",
    subcategory: "hands",
  },
  {
    code: ["1F64F"],
    emoji: "🙏",
    name: "folded hands",
    category: "People & Body",
    subcategory: "hands",
  },
  {
    code: ["1F44B"],
    emoji: "👋",
    name: "waving hand",
    category: "People & Body",
    subcategory: "hand-fingers-open",
  },
  {
    code: ["1F91D"],
    emoji: "🤝",
    name: "handshake",
    category: "People & Body",
    subcategory: "hands",
  },
  {
    code: ["1F44C"],
    emoji: "👌",
    name: "OK hand",
    category: "People & Body",
    subcategory: "hand-fingers-partial",
  },
  {
    code: ["270C", "FE0F"],
    emoji: "✌️",
    name: "victory hand",
    category: "People & Body",
    subcategory: "hand-fingers-partial",
  },
  {
    code: ["1F91E"],
    emoji: "🤞",
    name: "crossed fingers",
    category: "People & Body",
    subcategory: "hand-fingers-crossed",
  },
  {
    code: ["1F448"],
    emoji: "👈",
    name: "backhand index pointing left",
    category: "People & Body",
    subcategory: "hand-single-finger",
  },
  {
    code: ["1F449"],
    emoji: "👉",
    name: "backhand index pointing right",
    category: "People & Body",
    subcategory: "hand-single-finger",
  },
  {
    code: ["1F446"],
    emoji: "👆",
    name: "backhand index pointing up",
    category: "People & Body",
    subcategory: "hand-single-finger",
  },
  {
    code: ["1F447"],
    emoji: "👇",
    name: "backhand index pointing down",
    category: "People & Body",
    subcategory: "hand-single-finger",
  },
  {
    code: ["261D", "FE0F"],
    emoji: "☝️",
    name: "index pointing up",
    category: "People & Body",
    subcategory: "hand-single-finger",
  },
  {
    code: ["270A"],
    emoji: "✊",
    name: "raised fist",
    category: "People & Body",
    subcategory: "hand-fingers-closed",
  },
  {
    code: ["1F44A"],
    emoji: "👊",
    name: "oncoming fist",
    category: "People & Body",
    subcategory: "hand-fingers-closed",
  },
  {
    code: ["1F91B"],
    emoji: "🤛",
    name: "left-facing fist",
    category: "People & Body",
    subcategory: "hand-fingers-closed",
  },
  {
    code: ["1F4AA"],
    emoji: "💪",
    name: "flexed biceps",
    category: "People & Body",
    subcategory: "body-parts",
  },
  {
    code: ["1FAF6"],
    emoji: "🫶",
    name: "heart hands",
    category: "People & Body",
    subcategory: "hands",
  },
  {
    code: ["2764", "FE0F"],
    emoji: "❤️",
    name: "red heart",
    category: "Symbols",
    subcategory: "emotion",
  },
  {
    code: ["1F494"],
    emoji: "💔",
    name: "broken heart",
    category: "Symbols",
    subcategory: "emotion",
  },
  {
    code: ["1F495"],
    emoji: "💕",
    name: "two hearts",
    category: "Symbols",
    subcategory: "emotion",
  },
  {
    code: ["1F4AF"],
    emoji: "💯",
    name: "hundred points",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["1F525"],
    emoji: "🔥",
    name: "fire",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["2728"],
    emoji: "✨",
    name: "sparkles",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["2B50"],
    emoji: "⭐",
    name: "star",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["1F4AB"],
    emoji: "💫",
    name: "dizzy",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["2705"],
    emoji: "✅",
    name: "check mark button",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["274C"],
    emoji: "❌",
    name: "cross mark",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["2757"],
    emoji: "❗",
    name: "exclamation mark",
    category: "Symbols",
    subcategory: "punctuation",
  },
  {
    code: ["2753"],
    emoji: "❓",
    name: "question mark",
    category: "Symbols",
    subcategory: "punctuation",
  },
  {
    code: ["1F389"],
    emoji: "🎉",
    name: "party popper",
    category: "Symbols",
    subcategory: "celebration",
  },
  {
    code: ["1F38A"],
    emoji: "🎊",
    name: "confetti ball",
    category: "Symbols",
    subcategory: "celebration",
  },
  {
    code: ["1F4A4"],
    emoji: "💤",
    name: "zzz",
    category: "Symbols",
    subcategory: "other-symbol",
  },
  {
    code: ["26BD"],
    emoji: "⚽",
    name: "soccer ball",
    category: "Activities",
    subcategory: "sport",
  },
  {
    code: ["1F3C0"],
    emoji: "🏀",
    name: "basketball",
    category: "Activities",
    subcategory: "sport",
  },
  {
    code: ["1F3C8"],
    emoji: "🏈",
    name: "american football",
    category: "Activities",
    subcategory: "sport",
  },
  {
    code: ["1F3AE"],
    emoji: "🎮",
    name: "video game",
    category: "Activities",
    subcategory: "game",
  },
  {
    code: ["1F3AF"],
    emoji: "🎯",
    name: "direct hit",
    category: "Activities",
    subcategory: "game",
  },
  {
    code: ["1F3C6"],
    emoji: "🏆",
    name: "trophy",
    category: "Activities",
    subcategory: "award-medal",
  },
  {
    code: ["1F355"],
    emoji: "🍕",
    name: "pizza",
    category: "Food & Drink",
    subcategory: "food-prepared",
  },
  {
    code: ["1F354"],
    emoji: "🍔",
    name: "hamburger",
    category: "Food & Drink",
    subcategory: "food-prepared",
  },
  {
    code: ["1F32E"],
    emoji: "🌮",
    name: "taco",
    category: "Food & Drink",
    subcategory: "food-prepared",
  },
  {
    code: ["1F35F"],
    emoji: "🍟",
    name: "french fries",
    category: "Food & Drink",
    subcategory: "food-prepared",
  },
  {
    code: ["1F37F"],
    emoji: "🍿",
    name: "popcorn",
    category: "Food & Drink",
    subcategory: "food-prepared",
  },
  {
    code: ["1F369"],
    emoji: "🍩",
    name: "doughnut",
    category: "Food & Drink",
    subcategory: "food-sweet",
  },
  {
    code: ["1F436"],
    emoji: "🐶",
    name: "dog face",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F431"],
    emoji: "🐱",
    name: "cat face",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F430"],
    emoji: "🐰",
    name: "rabbit face",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F98A"],
    emoji: "🦊",
    name: "fox",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F43B"],
    emoji: "🐻",
    name: "bear",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F43C"],
    emoji: "🐼",
    name: "panda",
    category: "Animals & Nature",
    subcategory: "animal-mammal",
  },
  {
    code: ["1F697"],
    emoji: "🚗",
    name: "automobile",
    category: "Travel & Places",
    subcategory: "transport-ground",
  },
  {
    code: ["1F68C"],
    emoji: "🚌",
    name: "bus",
    category: "Travel & Places",
    subcategory: "transport-ground",
  },
  {
    code: ["1F680"],
    emoji: "🚀",
    name: "rocket",
    category: "Travel & Places",
    subcategory: "transport-air",
  },
  {
    code: ["2708", "FE0F"],
    emoji: "✈️",
    name: "airplane",
    category: "Travel & Places",
    subcategory: "transport-air",
  },
  {
    code: ["1F3E0"],
    emoji: "🏠",
    name: "house",
    category: "Travel & Places",
    subcategory: "place-building",
  },
  {
    code: ["1F30D"],
    emoji: "🌍",
    name: "globe showing Europe-Africa",
    category: "Travel & Places",
    subcategory: "place-map",
  },
  {
    code: ["1F4F1"],
    emoji: "📱",
    name: "mobile phone",
    category: "Objects",
    subcategory: "phone",
  },
  {
    code: ["1F4BB"],
    emoji: "💻",
    name: "laptop",
    category: "Objects",
    subcategory: "computer",
  },
  {
    code: ["1F4F7"],
    emoji: "📷",
    name: "camera",
    category: "Objects",
    subcategory: "light-video",
  },
  {
    code: ["1F3A7"],
    emoji: "🎧",
    name: "headphone",
    category: "Objects",
    subcategory: "music",
  },
  {
    code: ["1F4A1"],
    emoji: "💡",
    name: "light bulb",
    category: "Objects",
    subcategory: "light-video",
  },
  {
    code: ["1F512"],
    emoji: "🔒",
    name: "locked",
    category: "Objects",
    subcategory: "lock",
  },
  {
    code: ["1F511"],
    emoji: "🔑",
    name: "key",
    category: "Objects",
    subcategory: "lock",
  },
  {
    code: ["1F4B0"],
    emoji: "💰",
    name: "money bag",
    category: "Objects",
    subcategory: "money",
  },
  {
    code: ["1F3C1"],
    emoji: "🏁",
    name: "chequered flag",
    category: "Flags",
    subcategory: "flag",
  },
];
