/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewRouteImport } from './routes/new'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AichatRouteImport } from './routes/aichat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CConversationIdRouteImport } from './routes/c.$conversationId'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'
import { Route as ApiThreadSummaryRouteImport } from './routes/api/thread-summary'
import { Route as ApiAichatRouteImport } from './routes/api/aichat'
import { Route as CConversationIdReplyRouteImport } from './routes/c.$conversationId.reply'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AichatRoute = AichatRouteImport.update({
  id: '/aichat',
  path: '/aichat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CConversationIdRoute = CConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadSummaryRoute = ApiThreadSummaryRouteImport.update({
  id: '/api/thread-summary',
  path: '/api/thread-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAichatRoute = ApiAichatRouteImport.update({
  id: '/api/aichat',
  path: '/api/aichat',
  getParentRoute: () => rootRouteImport,
} as any)
const CConversationIdReplyRoute = CConversationIdReplyRouteImport.update({
  id: '/reply',
  path: '/reply',
  getParentRoute: () => CConversationIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aichat': typeof AichatRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/threads': typeof ThreadsRoute
  '/api/aichat': typeof ApiAichatRoute
  '/api/thread-summary': typeof ApiThreadSummaryRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRouteWithChildren
  '/c/$conversationId/reply': typeof CConversationIdReplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aichat': typeof AichatRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/threads': typeof ThreadsRoute
  '/api/aichat': typeof ApiAichatRoute
  '/api/thread-summary': typeof ApiThreadSummaryRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRouteWithChildren
  '/c/$conversationId/reply': typeof CConversationIdReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/aichat': typeof AichatRoute
  '/mcp': typeof McpRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/threads': typeof ThreadsRoute
  '/api/aichat': typeof ApiAichatRoute
  '/api/thread-summary': typeof ApiThreadSummaryRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRouteWithChildren
  '/c/$conversationId/reply': typeof CConversationIdReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/aichat'
    | '/mcp'
    | '/new'
    | '/search'
    | '/threads'
    | '/api/aichat'
    | '/api/thread-summary'
    | '/assets/$'
    | '/c/$conversationId'
    | '/c/$conversationId/reply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/aichat'
    | '/mcp'
    | '/new'
    | '/search'
    | '/threads'
    | '/api/aichat'
    | '/api/thread-summary'
    | '/assets/$'
    | '/c/$conversationId'
    | '/c/$conversationId/reply'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/aichat'
    | '/mcp'
    | '/new'
    | '/search'
    | '/threads'
    | '/api/aichat'
    | '/api/thread-summary'
    | '/assets/$'
    | '/c/$conversationId'
    | '/c/$conversationId/reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AichatRoute: typeof AichatRoute
  McpRoute: typeof McpRoute
  NewRoute: typeof NewRoute
  SearchRoute: typeof SearchRoute
  ThreadsRoute: typeof ThreadsRoute
  ApiAichatRoute: typeof ApiAichatRoute
  ApiThreadSummaryRoute: typeof ApiThreadSummaryRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  CConversationIdRoute: typeof CConversationIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aichat': {
      id: '/aichat'
      path: '/aichat'
      fullPath: '/aichat'
      preLoaderRoute: typeof AichatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$conversationId': {
      id: '/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof CConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thread-summary': {
      id: '/api/thread-summary'
      path: '/api/thread-summary'
      fullPath: '/api/thread-summary'
      preLoaderRoute: typeof ApiThreadSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aichat': {
      id: '/api/aichat'
      path: '/api/aichat'
      fullPath: '/api/aichat'
      preLoaderRoute: typeof ApiAichatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$conversationId/reply': {
      id: '/c/$conversationId/reply'
      path: '/reply'
      fullPath: '/c/$conversationId/reply'
      preLoaderRoute: typeof CConversationIdReplyRouteImport
      parentRoute: typeof CConversationIdRoute
    }
  }
}

interface CConversationIdRouteChildren {
  CConversationIdReplyRoute: typeof CConversationIdReplyRoute
}

const CConversationIdRouteChildren: CConversationIdRouteChildren = {
  CConversationIdReplyRoute: CConversationIdReplyRoute,
}

const CConversationIdRouteWithChildren = CConversationIdRoute._addFileChildren(
  CConversationIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AichatRoute: AichatRoute,
  McpRoute: McpRoute,
  NewRoute: NewRoute,
  SearchRoute: SearchRoute,
  ThreadsRoute: ThreadsRoute,
  ApiAichatRoute: ApiAichatRoute,
  ApiThreadSummaryRoute: ApiThreadSummaryRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  CConversationIdRoute: CConversationIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
