/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CConversationIdRouteImport } from './routes/c.$conversationId'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CConversationIdRoute = CConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$': typeof AssetsSplatRoute
  '/c/$conversationId': typeof CConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assets/$' | '/c/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets/$' | '/c/$conversationId'
  id: '__root__' | '/' | '/assets/$' | '/c/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  CConversationIdRoute: typeof CConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$conversationId': {
      id: '/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof CConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  CConversationIdRoute: CConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
